let products=[],cart=[],cat="All";
const $=id=>document.getElementById(id), money=n=>"₹"+Number(n).toLocaleString("en-IN");
async function init(){products=await (await fetch("/api/products")).json();renderCats();render();updateCart()}
function renderCats(){let cats=["All",...new Set(products.map(p=>p.category))];$("cats").innerHTML=cats.map(c=>`<button class="cat ${c===cat?"active":""}" onclick="cat='${c.replaceAll("'","\\'")}';renderCats();render()">${c}</button>`).join("")}
function render(){let q=($("q").value||"").toLowerCase();let ps=products.filter(p=>(cat==="All"||p.category===cat)&&(`${p.name} ${p.category} ${p.unit}`.toLowerCase().includes(q)));$("count").textContent=ps.length+" items";$("products").innerHTML=ps.map(p=>`<article class="card"><div class="pic">${p.icon}</div><div class="body"><b>${p.name}</b><div class="muted">${p.unit} • ${p.category}</div><div class="bottom"><span class="price">${money(p.price)}</span><button class="add" onclick="add(${p.id})">+ Add</button></div></div></article>`).join("")||"<p class='muted'>No products found.</p>"}
function add(id){let x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});updateCart()}
function change(id,d){let x=cart.find(i=>i.id===id);if(x){x.qty+=d;if(x.qty<1)cart=cart.filter(a=>a.id!==id)}updateCart();showCart()}
function updateCart(){$("num").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function showCart(){$("cart").classList.remove("hide");let total=0;$("cartItems").innerHTML=cart.length?cart.map(x=>{let p=products.find(y=>y.id===x.id);total+=p.price*x.qty;return `<div class="cartline"><div><b>${p.name}</b><div class="muted">${money(p.price)} × ${x.qty}</div></div><div class="qty"><button onclick="change(${p.id},-1)">−</button> ${x.qty} <button onclick="change(${p.id},1)">+</button></div></div>`}).join(""):"<p class='muted'>Your cart is empty.</p>";$("total").textContent=money(total)}
function closeCart(){$("cart").classList.add("hide")} function checkout(){if(!cart.length)return;closeCart();$("checkout").classList.remove("hide")}function closeCheckout(){$("checkout").classList.add("hide")}
$("cartBtn").onclick=showCart;$("q").oninput=render;
$("form").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);let r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),phone:f.get("phone"),address:f.get("address"),notes:f.get("notes"),items:cart})});let j=await r.json();if(!r.ok)return alert(j.error||"Could not place order");cart=[];updateCart();closeCheckout();$("orderMsg").textContent=`Your order #${j.orderId} was received. Total: ${money(j.total)}. Please keep cash ready for delivery.`;$("done").classList.remove("hide")};
init();